name: Deploy over SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Copy files to remote server
        run: |
          scp -i ~/.ssh/id_rsa -r . ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

      - name: Deploy and restart container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            cd ${{ secrets.TARGET_DIR }}
            docker build -t beanstalk-app .
            docker stop beanstalk-app || true
            docker rm beanstalk-app || true
            docker run -d -p 80:80 --name beanstalk-app beanstalk-app
          EOF
